name: percact23
channels:
  - cogsci
  - conda-forge
dependencies:
  - opensesame
  - opensesame-extension-osweb
  - opensesame-extension-updater
  - opensesame-plugin-psychopy
  - pygaze
  - python=3.8.17
  - pip
  - pyqtwebengine
  - qtconsole
  - rapunzel
  - wxpython
  - pip:
      - pygame
      - soundfile
      - tomlkit
      - http://files.cogsci.nl/expyriment-0.10.0+opensesame2-py3-none-any.whl
      - psychopy
      - psychopy-sounddevice
      - https://github.com/PascalKieslich/mousetrap-os/archive/master.zip
